name: nombre_del_proyecto
description: Una nueva aplicación Flutter

publish_to: 'none' # Remove this line if you are planning to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Paquete para gráficos
  fl_chart: ^0.40.0

  # Paquete para generar PDF
  pdf: ^3.6.0

  # Paquete para generar archivos Excel
  excel: ^2.0.3

  # Para acceder al almacenamiento del dispositivo
  path_provider: ^2.0.2

  # Para guardar los archivos generados
  file_saver: ^1.0.2

  # Paquete para acceder al nivel de batería del dispositivo
  battery_plus: ^2.0.0

  # Paquete para enviar correos electrónicos
  flutter_email_sender: ^5.0.2

  # Paquete para tutorial interactivo de bienvenida
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tutorial1.png
    - assets/tutorial2.png
    - assets/tutorial3.png